	// Add content key/value pairs here
	// Content variables are ordered alphabetically
	module.exports = {
		// add key/pairs like the line below
		// variable: 'content',
		notificationsHeadingOne: 'Manage notifications',
		notificationsLedeParagraph: 'All intelligence is available on the tool but you can be notified about specific transactions you want to monitor.',
		notificationsBulletHeading: 'You can be notified about:',
		notificationsBulletListItem1: 'credits and disbursements',
		notificationsBulletListItem2: 'frequency of transactions',
		notificationsBulletListItem3: 'a prisoner',
		notificationsBulletListItem4: 'a debit card / bank account',
		notificationsBulletListItem5: '',
		notificationsParagraph2: 'You can also choose to get notifications by email.',
		notificationsButtonText: 'Set up notifications',
		monitoredTransactionsHeadingOne: 'Monitored transactions',
		monitoredTransactionsQuestion: 'Get notifications for the transactions you\'re  currently monitoring.',
		monitoredTransactionsHint: 'This includes prisoners, debit cards and bank accounts.',
		creditsAndDisbursmentsHeadingOne: 'Credits and disbursements',
		notificationsLedeParagraph:'Get notifications for amounts of money sent in as credits and sent out as disbursements. Amounts that are:',
		creditsAndDisbursmentsQuestionOne: 'Not a whole number?',
		creditsAndDisbursmentsHintOne: 'Eg, £25.19',
		creditsAndDisbursmentsQuestionTwo: 'Over £200?',
		creditsAndDisbursmentsHintTwo: '',
		frequencyOfTransactionsHeadingOne: 'Frequency of transactions',
		frequencyOfTransactionsLedeParagraph: 'When money is credited or disbursed more often that usual, get notifications for:',
		frequencyOfTransactionsHeadingTwo: '',
		frequencyOfTransactionsQuestionOne: 'XX credits from the same debit card or bank account to any prisoner?',
		frequencyOfTransactionsQuestionOneHint: 'If you select Yes, you can determine the amount and frequency.',
		frequencyOfTransactionsQuestionTwo: 'XX disbursements from the same debit card or bank account to any prisoner?',
		frequencyOfTransactionsQuestionTwoHint: 'If you select Yes, you can determine the amount and frequency.',
		prisonersHeadingOne: 'Frequent use by prisoners',
		prisonersLedeParagraph: 'If a prisoner is sent or sends out more money than usual, get notifications when: ',
		prisonersHeadingTwo: '',
		prisonersQuestionOne: 'That prisoner is sent money from XX debit cards or bank acounts within a XX weeks?',
		prisonersQuestionTwo: 'That prisoner sends out money from XX debit cards or bank acounts within a XX weeks?',
		debitCardOrBankAccountHeadingOne: 'Debit cards or bank accounts',
		debitCardOrBankAccountLedeParagraph: 'When money comes in from or goes out to many debit cards or bank accounts, get notifications about:',
		debitCardOrBankAccountHeadingTwo: '',
		debitCardOrBankAccountQuestionOne: 'Money coming in from XX debit cards or bank accounts within XX weeks?',
		debitCardOrBankAccountQuestionTwo: 'Money going out from XX debit cards or bank accounts within XX weeks?',
		emailFrequencyHeadingOne: 'Notifications by email ',
		prisonersLedeParagraph: 'Notifications will be updated daily on your notifications screen. If you would also like them sent to you in batches by email, how often?',
		emailFrequencyValueOne: 'Once a day',
		emailFrequencyValueTwo: 'Once a week',
		emailFrequencyValueThree: 'I do not want email notifications',
		checkYourAnswersHeadingOne: 'Notifications',
		checkYourAnswersLedeParagraph: 'All intelligence is available on the tool at all times but you can set up email notifications for specific transactions.',
		checkYourAnswersHeadingTwo: 'Notifications',
	};
	// }
