	// Add content key/value pairs here
	// Content variables are ordered alphabetically
	module.exports = {
		// add key/pairs like the line below
		// variable: 'content',
		notificationsHeadingOne: 'Check your notifications',
		notificationsLedeParagraph: 'All intelligence is available on the tool but you can be notified about specific transactions you want to monitor or are already monitoring.',
		notificationsBulletHeading: 'You can be notified about:',
		notificationsBulletListItem1: 'credits and disbursements',
		notificationsBulletListItem2: 'frequency of transactions',
		notificationsBulletListItem3: 'what a prisoner sends or receives',
		notificationsBulletListItem4: 'a debit card / bank account',
		notificationsParagraph2: 'You can also choose to get new notifications by email.',
		notificationsButtonText: 'Set up notifications',
		monitoredTransactionsHeadingOne: 'Monitored transactions',
		monitoredTransactionsLedeParagraph: 'Notifications for the transactions you\'re  already monitoring - prisoners, debit cards and bank accounts - in your prisons.',
		creditsAndDisbursmentsHeadingOne: 'Credits and disbursements',
		creditsAndDisbursmentsBulletHeading:'Notifications for credits and disbursements that are:',
		creditsAndDisbursmentsQuestionOne: 'Not a whole number',
		creditsAndDisbursmentsHintOne: 'Eg, £25.19',
		creditsAndDisbursmentsQuestionTwo: 'Over £120',
		creditsAndDisbursmentsHintTwo: '',
		frequencyOfTransactionsHeadingOne: 'Frequency of transactions',
		frequencyOfTransactionsLedeParagraph: 'Notifications when money is credited or disbursed more often that usual.',
		frequencyOfTransactionsHeadingTwo: '',
		frequencyOfTransactionsQuestionOne: '4 or more credits sent by a single debit card or bank account in last 4 weeks',
		frequencyOfTransactionsQuestionOneHint: 'If you select Yes, you can determine the amount and frequency.',
		frequencyOfTransactionsQuestionTwo: '4 or more disbursements sent to a single bank account in last 4 weeks',
		frequencyOfTransactionsQuestionTwoHint: 'If you select Yes, you can determine the amount and frequency.',
		prisonersHeadingOne: 'Prisoner transactions',
		prisonersLedeParagraph: 'Notifications when a prisoner receives or sends out more money than usual.',
		prisonersHeadingTwo: '',
		prisonersQuestionOne: 'Money from 4 or more debit cards or bank accounts in last 4 weeks',
		prisonersQuestionTwo: 'Money to 4 or more bank accounts in last 4 weeks',
		debitCardOrBankAccountHeadingOne: 'A debit card or bank account',
		debitCardOrBankAccountLedeParagraph: 'Notifications when a debit card or bank account is used more often than usual.',
		debitCardOrBankAccountHeadingTwo: '',
		debitCardOrBankAccountQuestionOne: 'Money from a debit card or bank account to more than 4 prisoners in last 4 weeks',
		debitCardOrBankAccountQuestionTwo: 'Money sent to a bank account by more than 4 prisoners in last 4 weeks',
		emailFrequencyHeadingOne: 'Do you want your new notifications by email? ',
		emailFrequencyLedeParagraph: '',
		emailFrequencyValueOne: 'Yes, once a day',
		emailFrequencyValueTwo: 'Yes, once a week',
		emailFrequencyValueThree: 'No, I can check the notifications page',
		checkYourAnswersHeadingOne: 'Notifications',
		checkYourAnswersLedeParagraph: 'All intelligence is available on the tool at all times but you can set up email notifications for specific transactions.',
		checkYourAnswersHeadingTwo: 'Notifications',
	};
	// }
